name: Deploy Application

on:
  push:
    branches:
      - main  # This will trigger the action on every push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # This defines the environment to run on (Linux-based runner)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This checks out your code so you can work with it

      - name: Set up environment variable for GROQ
        run: echo "GROQ=${{ secrets.GROQ }}" >> .env  # This writes the secret into the .env file

      - name: Display .env content (for debugging)
        run: cat .env  # Optional, useful for debugging to ensure the secret was added

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install Python dependencies, adjust if needed

      - name: Run the application (example for Python)
        run: |
          python app.py  # Replace with your actual application command
